<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.gettyio.gim</groupId>
    <artifactId>wxauto4j</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>wxauto4j-app</artifactId>
  <name>wxauto4j-app</name>
  <description>微信自动化运行主体</description>

  <dependencies>
    <dependency>
      <groupId>com.gettyio.gim</groupId>
      <artifactId>wxauto4j-lib</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>io.getbit.app.Main</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <mainClass>io.getbit.app.Main</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
